#!/bin/bash

# Command to filter out cuts.txt generated by tsppddl into a file good for this script:
# cat cuts.txt | grep "CAP_CUT: " | sed 's/CAP_CUT: //' > cuts_for_rb.txt

if [[ -z "$1" ]]
then
    echo "I need the cuts file name as a parameter"
    exit
else
  cuts_file=$1
fi

reading_vars=true
ruby_script="/tmp/script.rb"

while read l
do
    if [[ $reading_vars = "true" ]]
    then
        echo "$l" > $ruby_script
        reading_vars=false
    else
        {
            echo "if $l"
            echo "  puts \"This constraint was not violated by the fractional solution\""
            echo "  exit 1"
            echo "else"
            echo "  exit 0"
            echo "end"
        } >> $ruby_script
        
        ruby $ruby_script
        
        if [[ "$?" = "1" ]]
        then
            echo "Wrong cut found:"
            echo "$l"
        fi
        
        reading_vars=true
    fi
done < "$cuts_file"